version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: staff_management
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
    container_name: api
    restart: always
    environment:
      DATABASE_URL: "postgresql://postgres:1@postgres:5432/staff_management"
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data: